### ISSUE TITLE
webhook broken?

### ISSUE THREAD

**Issue by niodamian** [kibook/logmanager#3]
your webhook is not working ...
i tried the chat fuction but doesnt send anything

**Comment by kibook** [comment]
I'm using the webhook myself, so I don't think it's simply broken. What do you mean by the "chat fuction"?

**Comment by niodamian** [comment]
the script is working just doesnt sent the results on discord.... like lets say my chat channel doesnt shows up your info ..only inside database shows the chat and yet not the command like /me ...

**Comment by kibook** [comment]
Have you entered the webhook correctly in `config.lua`? Do you receive any errors in your server console?

**Comment by kibook** [comment]
> only inside database shows the chat and yet not the command like /me ...

See my comments in #2. By default, logmanager taps into the default chat `chatMessage` event, which is triggered whenever a chat message is sent, but not a valid command chat message like /me.

**Comment by niodamian** [comment]
yes my webhook is working its corrent i use other script for chat ..i just needed to test yours .... 

i have 0 errors and thats the thing..haha thats why i m asking you otherwise i could locate the problem .... doesnt send the webhooks

**Comment by kibook** [comment]
Make you're using the latest commit, and make sure `Config.webhook` is set in [config.lua](https://github.com/kibook/logmanager/blob/master/config.lua). It's commented out by default so make sure to uncomment it:

Before:
```lua
-- Discord webhook to post log messages to
--Config.webhook = ""
```

After:
```lua
-- Discord webhook to post log messages to
Config.webhook = "https://https://discord.com/api/webhooks/<webhook ID>/<webhook token>"
```

I'm using the webhook right now and it's working for me:
https://streamable.com/t2ohwm
