### ISSUE TITLE
Couldn't start resource logmanager

### ISSUE THREAD

**Issue by Musiker15** [kibook/logmanager#4]
Hey, i get following error in startup:

`[    c-resources-core] Could not find dependency ghmattimysql for resource logmanager.`
`[ citizen-server-impl] Couldn't start resource logmanager.`

Do you know how to fix that?
Using Debian 10 on Rootserver.

**Comment by kibook** [comment]
This resource has a few dependencies:
- [ghmattimysql](https://github.com/GHMatti/ghmattimysql) for SQL database interaction (also requires that you have configured an SQL database on your server).
- [httpmanager](https://github.com/kibook/httpmanager) for the web user interface.
- [discord_rest](https://github.com/kibook/discord_rest) for posting logs to Discord.

These are also listed in the `fxmanifest.lua`:
```lua
dependencies {
	"ghmattimysql",
	"httpmanager",
	"discord_rest"
}
```

**Comment by Musiker15** [comment]
Okay so I need to implement `ghmattimysql` to my Fivem server?
Like this one: https://github.com/GHMatti/ghmattimysql?
